---
title: "time_series_analysis_with_state_space_model"
author: "Kousuke Kikuchi"
date: "July 7, 2015"
output: html_document
---

# 9. 状態空間モデルによる時系列の解析
- 時系列解析で用いられている様々なモデルを状態空間モデルで統合的に扱うことができる
- 水準の変化をシステムモデル、観測誤差を観測モデルで表す。
- 予測ではなく、説明にかなり大きな重きを置いた手法
- 予測を立てる。観測誤差からカウマンフィルターを使って補正していく。
    - 状態を補正することで、徐々に精度を上げていく方法
    - TSSSではtsmoothという関数である。

### 9.1 状態空間モデル
- 直接には観測できないxnはstateと呼ばれるベクトル
- ynはシステムノイズと呼ばれるが、中身はホワイトノイズ
- wnは観測ノイズ。平均ベクトル0、分散共分散行列Rnに従うl次元のホワイトノイズ
- ynが観測される仕組みを表現する回帰モデルと考えると、状態xnは回帰係数となる
- xnを推定する際には、信号発生のメカニズムを表すモデルを示す
    - これらのパラメータをカウマンフィルタに入れて、補正していく
$$
x_{n} = F_{n}x_{n} + G_{n}v_{n}\\
y_{n} = H_{n} + \omega_{n}\\
$$



### 9.2 カウマンフィルタによる状態の推定
- 状態空間モデルの重要な問題は、ynの観測値に基づいて状態xnの推定を行うこと
    - 観測値に基づいて、状態xnの推定を行う。
        - 観測区間より先の状態を推定する場合は、予測と呼ばれる
        - 現在の状態を推定する場合、フィルタと呼ばれる
        - 現在までの観測値に基づいて過去の状態を推定する場合は、平滑化（smoothing）と呼ばれる
    - 状態推定問題は観測値が与えられたしたでの状態の条件付き分布 p(xn|Yj)を求める
    - この計算を効率的に行うのがカウマンフィルタ
        - 一期先予測とフィルタを交互に繰り返すことで、目的とする推定を行う
        - イメージとしては、一つ先の予測をある時点でする。
        - そこから振り返って、パラメータの更新を行う
        - 一歩進む
    
### 9.3 平準化のアルゴリズム
- 固定区間平準化
    - 平準はすべての観測値を用いているので、精度の良い推定ができる
    - カウマンフィルタを実行したあとに使う
    
### 9.4 状態の長期予測
- 一期先予測の方法を繰り返すことで長期予測が可能

### 9.5 時系列の予測
- 状態の予測を使って時系列の予測が可能
- 長期的な予測をする場合、綿密なデータモデリングが必要
    - 一つ先程度ならあまり変わらないが

### 9.6 時系列モデルの尤度計算とパラメータ推定
- 要するにどのモデルが一番いいのという話

### 9.7 欠測値の補間
- 欠測値を０や平均値で補うのはダメ
- 時系列モデルがわかっている場合はそのモデルを利用して欠測値の補間を行う

### 実際にやってみよう
```{r fig.width=20, fig.height=10, message=FALSE}
library(TSSS)
example(tsmooth) #の内容をコピペした上で、コメントを書く
## AR model (l=1, k=1)
```

